# 基础镜像
FROM redis
# author
MAINTAINER smartLive

# 挂载目录
VOLUME /home/smartLive/redis
# 创建目录
RUN mkdir -p /home/smartLive/redis
# 指定路径
WORKDIR /home/smartLive/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/smartLive/redis/redis.conf
