# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER smartLive

# 挂载目录
VOLUME /home/smartLive
# 创建目录
RUN mkdir -p /home/smartLive
# 指定路径
WORKDIR /home/smartLive
# 复制jar文件到路径
COPY ./jar/smartLive-modules-system.jar /home/smartLive/smartLive-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","smartLive-modules-system.jar"]