# 基础镜像
FROM nginx
# author
MAINTAINER smartLive

# 挂载目录
VOLUME /home/smartLive/projects
# 创建目录
RUN mkdir -p /home/smartLive/projects/smartLive-ui\
    && mkdir -p /home/smartLive/projects/smartLive-html
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/smartLive/projects/smartLive-ui
COPY ./html/html /home/smartLive/projects/smartLive-html
