# 基础镜像
FROM  openjdk:17-jdk
# author
MAINTAINER smartLive

# 挂载目录
VOLUME /home/smartLive
# 创建目录
RUN mkdir -p /home/smartLive
# 指定路径
WORKDIR /home/smartLive
# 复制jar文件到路径
COPY ./jar/smartLive-modules-job.jar /home/smartLive/smartLive-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","smartLive-modules-job.jar"]