import random
import datetime
import os

# --- Configuration ---
NUM_USERS = 200
NUM_SHOPS = 500
NUM_PRODUCTS = 2000
NUM_BLOGS = 2000
NUM_REVIEWS = 3000
NUM_ORDERS = 5000
NUM_FOLLOWS = 2000
NUM_LIKES = 5000

OUTPUT_DIR = 'd:/smart-live/smart-live-Cloud/sql/test_data'
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# --- Helper Functions ---
def get_now():
    return datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

def random_date(start_year=2024, end_year=2026):
    start = datetime.datetime(start_year, 1, 1)
    end = datetime.datetime(end_year, 12, 31)
    return (start + datetime.timedelta(seconds=random.randint(0, int((end - start).total_seconds())))).strftime('%Y-%m-%d %H:%M:%S')

def get_audit_status():
    """
    Returns (status, audit_status)
    70% Approved: (1, 1)
    20% Pending: (0, 0)
    10% Rejected: (2, 2)
    """
    r = random.random()
    if r < 0.7:
        return 1, 1
    elif r < 0.9:
        return 0, 0
    else:
        return 2, 2

# --- Data Generation Stacks ---
db_sql = {
    'smart-live_user': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_user`;"],
    'smart-live_shop': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_shop`;"],
    'smart-live_system': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_system`;"],
    'smart-live_product': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_product`;"],
    'smart-live_blog': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_blog`;"],
    'smart-live_order': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_order`;"],
    'smart-live_interaction': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_interaction`;"],
    'smart-live_points': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_points`;"],
    'smart-live_audit': ["SET FOREIGN_KEY_CHECKS = 0;", "USE `smart-live_audit`;"]
}

# 1. Users (App Users)
BCRYPT_PASSWORD = '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2'
user_ids = []
for i in range(1, NUM_USERS + 1):
    phone = f"13{random.randint(0, 9):01d}{random.randint(10000000, 99999999)}"
    nick = f"User_{i}"
    user_ids.append(i)
    db_sql['smart-live_user'].append(f"INSERT INTO `user` (`id`, `phone`, `password`, `nick_name`, `icon`) VALUES ({i}, '{phone}', '{BCRYPT_PASSWORD}', '{nick}', 'https://api.dicebear.com/7.x/avataaars/svg?seed={nick}');")
    city = random.choice(['上海', '北京', '深圳', '广州', '杭州', '成都', '佛山', '东莞', '中山'])
    db_sql['smart-live_user'].append(f"INSERT INTO `user_info` (`user_id`, `city`, `introduce`, `fans`, `followee`, `liked`, `gender`, `birthday`, `credits`, `level`, `audit_status`) VALUES ({i}, '{city}', 'Hello, I am {nick}', {random.randint(0, 500)}, {random.randint(0, 200)}, {random.randint(0, 1000)}, {random.randint(0, 1)}, '1990-01-01', {random.randint(0, 5000)}, {random.randint(0, 9)}, 1);")

def add_audit_task(biz_id, biz_type, submitter_id, status, content_name):
    """
    biz_type: 2-Shop, 3-Blog, 4-Voucher (Prod Cat 1), 5-Review, 6-GroupBuy (Prod Cat 2)
    """
    reason = "'内容违规'" if status == 2 else "NULL"
    content = f'{{"name": "{content_name}", "note": "Generated by script"}}'
    db_sql['smart-live_audit'].append(f"INSERT INTO `audit_task` (`biz_id`, `biz_type`, `submitter_id`, `status`, `reason`, `audit_content`, `create_time`) VALUES ({biz_id}, {biz_type}, {submitter_id}, {status}, {reason}, '{content}', '{get_now()}');")

# 2. Shops
shop_types = ["精致西餐", "地道中餐", "甜品饮品", "休闲娱乐", "酒店住宿", "美容美发", "运动健身", "火锅烧烤", "小吃快餐", "便利超市"]
for i, name in enumerate(shop_types, 1):
    db_sql['smart-live_shop'].append(f"INSERT INTO `shop_type` (`id`, `name`, `icon`, `sort`) VALUES ({i}, '{name}', 'type_{i}.png', {i});")

foshan_areas = ['禅城区', '南海区', '顺德区', '三水区', '高明区']
foshan_streets = ['祖庙', '桂城', '大良', '西南', '荷城', '石湾', '狮山', '容桂', '北滘', '乐从', '九江', '西樵', '丹灶', '里水']
for i in range(1, NUM_SHOPS + 1):
    t_id = random.randint(1, len(shop_types))
    area = random.choice(foshan_areas)
    street = random.choice(foshan_streets)
    name_suffix = random.choice(['大酒店', '饭店', '火锅店', '私房菜', '饮品店', '健身中心', '造型屋', '超市', '快餐店'])
    name = f"{street}{name_suffix}_{i}"
    x = 113.0 + random.random() * 0.3
    y = 23.0 + random.random() * 0.2
    status, audit_status = get_audit_status()
    db_sql['smart-live_shop'].append(f"INSERT INTO `shop` (`id`, `name`, `type_id`, `images`, `area`, `address`, `x`, `y`, `avg_price`, `score`, `open_hours`, `status`, `audit_status`) VALUES ({i}, '{name}', {t_id}, 'https://picsum.photos/seed/shop{i}/400/300', '{area}', '广东省佛山市{area}{street}街道{random.randint(1, 999)}号', {x:.6f}, {y:.6f}, {random.randint(20, 500)}, {random.randint(30, 50)}, '09:00-22:00', {status}, {audit_status});")
    # Audit Task for Shop (biz_type 2)
    add_audit_task(i, 2, 1, status, name)

# 3. System Users & Merchant Linkage
MERCHANT_ROLE_ID = 100
for i in range(1, NUM_SHOPS + 1):
    sys_user_id = 1000 + i
    user_name = f"merchant_{i}"
    db_sql['smart-live_system'].append(f"INSERT INTO `sys_user` (`user_id`, `dept_id`, `user_name`, `nick_name`, `password`, `status`, `create_time`) VALUES ({sys_user_id}, 100, '{user_name}', '商家_{i}', '{BCRYPT_PASSWORD}', '0', '{get_now()}');")
    db_sql['smart-live_system'].append(f"INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES ({sys_user_id}, {MERCHANT_ROLE_ID});")
    db_sql['smart-live_system'].append(f"INSERT INTO `sys_user_shop` (`user_id`, `shop_id`, `create_time`) VALUES ({sys_user_id}, {i}, '{get_now()}');")

# 4. Products
for i in range(1, NUM_PRODUCTS + 1):
    s_id = random.randint(1, NUM_SHOPS)
    price = random.randint(10, 1000)
    category = random.randint(1, 2)
    status, audit_status = get_audit_status()
    db_sql['smart-live_product'].append(f"INSERT INTO `product` (`id`, `shop_id`, `name`, `sub_title`, `price`, `original_price`, `category`, `activity_type`, `status`, `audit_status`, `stock`, `cover_img`, `create_time`) VALUES ({i}, '{s_id}', 'Product_{i}', '优质商品', {price}.00, {price+20}.00, {category}, 0, {status}, {audit_status}, {random.randint(10, 1000)}, 'https://picsum.photos/seed/prod{i}/400/400', '{random_date()}');")
    # Audit Task (4-Voucher, 6-GroupBuy)
    biz_type = 4 if category == 1 else 6
    add_audit_task(i, biz_type, 1000 + s_id, status, f"Product_{i}")

# 5. Blogs
for i in range(1, NUM_BLOGS + 1):
    u_id = random.randint(1, NUM_USERS)
    s_id = random.randint(1, NUM_SHOPS)
    status, audit_status = get_audit_status()
    db_sql['smart-live_blog'].append(f"INSERT INTO `blog` (`id`, `shop_id`, `type_id`, `user_id`, `title`, `images`, `content`, `liked`, `stared`, `comments`, `status`, `audit_status`, `create_time`) VALUES ({i}, {s_id}, 1, {u_id}, '探店达人{i}', 'https://picsum.photos/seed/blog{i}/600/400', '这家店真的很惊艳！强烈推荐给大家。', {random.randint(0, 1000)}, {random.randint(0, 200)}, {random.randint(0, 50)}, {status}, {audit_status}, '{random_date()}');")
    # Audit Task (3-Blog)
    add_audit_task(i, 3, u_id, status, f"探店达人{i}")

# 6. Orders
for i in range(1, NUM_ORDERS + 1):
    db_sql['smart-live_order'].append(f"INSERT INTO `order` (`id`, `user_id`, `source_type`, `source_id`, `pay_amount`, `amount`, `status`, `shop_id`, `create_time`) VALUES ({i}, {random.randint(1, NUM_USERS)}, 1, {random.randint(1, NUM_PRODUCTS)}, {random.randint(1000, 50000)}, {random.randint(1, 3)}, 2, '{random.randint(1, NUM_SHOPS)}', '{random_date()}');")

# 7. Interaction (Reviews, Follows, Likes)
for i in range(1, NUM_REVIEWS + 1):
    s_id = random.randint(1, NUM_SHOPS)
    u_id = random.randint(1, NUM_USERS)
    status, audit_status = get_audit_status()
    db_sql['smart-live_interaction'].append(f"INSERT INTO `review` (`id`, `user_id`, `shop_id`, `order_id`, `source_type`, `source_id`, `content`, `score`, `status`, `audit_status`, `create_time`) VALUES ({i}, {u_id}, {s_id}, {random.randint(1, NUM_ORDERS)}, 2, {s_id}, '味道很棒，服务热情！', {random.randint(3, 5)}, {status}, {audit_status}, '{random_date()}');")
    # Audit Task (5-Review)
    add_audit_task(i, 5, u_id, status, f"Review_{i}")

for i in range(1, NUM_FOLLOWS + 1):
    u1, u2 = random.sample(range(1, NUM_USERS+1), 2)
    db_sql['smart-live_interaction'].append(f"INSERT INTO `follow` (`user_id`, `source_id`, `source_type`, `create_time`) VALUES ({u1}, {u2}, 1, '{random_date()}');")
for i in range(1, NUM_LIKES + 1):
    db_sql['smart-live_interaction'].append(f"INSERT INTO `like_record` (`source_type`, `source_id`, `user_id`, `create_time`) VALUES ('2', {random.randint(1, NUM_BLOGS)}, {random.randint(1, NUM_USERS)}, '{random_date()}');")

# 8. Points
for i in range(1, NUM_USERS + 1):
    db_sql['smart-live_points'].append(f"INSERT INTO `user_points_wallet` (`user_id`, `balance`, `total_earned`, `consecutive_days`, `version`) VALUES ({i}, {random.randint(100, 5000)}, {random.randint(500, 10000)}, {random.randint(0, 15)}, 0);")

# --- Write Files ---
for db, lines in db_sql.items():
    lines.append("\nSET FOREIGN_KEY_CHECKS = 1;")
    filename = f"{OUTPUT_DIR}/{db}.sql"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

print(f"Generated {len(db_sql)} SQL files in {OUTPUT_DIR}/ (Total Records Expanded with Audit Tasks)")

